#ifdef SPIKECOREC_CUDA
#include <cuda_runtime.h>
#elif defined(SPIKECOREC_METAL)
#include <Metal/Metal.hpp>
#endif

#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>

#include "spikecorec/nml/nml.h"
#include "spikecorec/nml/resolve.h"
#include "spikecorec/nml/model_specification.h"
#include "spikecorec/nml/cell_lowering.h"

using namespace std;
using namespace spikecorec;
using namespace spikecorec::nml;

// ── Cell dynamics -> IR lowering tests (ticket #50 [B2]) ─────────────────
//
// Each GLIF level is authored as a standalone LEMS `ComponentType` fixture
// (they are not in the vendored NeuroML2CoreTypes std-lib -- ticket #2's own
// GLIF1 fixture precedent, extended here with a `DerivedVariable`
// `select`/`reduce="add"` aggregation so `iSyn` is actually well-defined,
// per arch §3.2's "collapses to a `network_inputs` read" rule) and pushed
// through the whole front-end pipeline (parse -> resolve_and_lower ->
// build_model_specification), exactly like nml_tests.cpp/resolve_tests.cpp/
// model_specification_tests.cpp already do, before being handed to
// lower_cell_to_ir. Expected `.tick`/`.alloc` text below was generated by
// running the real lowering and hand-verifying every instruction against
// the equations documented alongside each fixture, then pinned down as a
// regression baseline -- not hand-derived independently of the
// implementation, the same practical approach ir_tests.cpp's own examples
// take with print_ir_program.
//
// Equations chosen for GLIF2-5 (arch/IR-spec only describe these at a
// conceptual level; ticket #50 explicitly invites a documented judgment
// call here, same as ticket #49's refractory-regime "sketch"):
//   - GLIF1: pure LIF, `dv/dt = (network_inputs + gL*(EL-v))/C`, fixed
//     `vth`/`vreset`, plus a fixed refractory period (the Allen GLIF1
//     definition includes one; the locked IR spec's own GLIF1 example omits
//     it purely for pedagogical brevity -- see the PlainLif fixture below,
//     which reproduces that exact example without a regime).
//   - GLIF2: LIF + a reset rule that depends on how far past threshold the
//     neuron went: `v <- vreset + resetScale*(v-vth)`, not a flat constant.
//   - GLIF3: LIF + two after-spike currents `asc1`/`asc2`, each with its own
//     linear decay (`-asc_k/tauAsc_k`) and an additive jump at spike time
//     (`asc_k <- asc_k + ascAdd_k`); their sum is a plain-value
//     `DerivedVariable` (`ascSum = asc1+asc2`) rather than a `Children`+
//     `reduce` aggregation over a dynamic list -- a fixed, small number of
//     named ASC variables is Phase-1-sufficient for GLIF3 and keeps the
//     fixture simple, per this ticket's own invited judgment call.
//   - GLIF4: LIF + an adaptive threshold: `theta` is a `StateVariable` (not
//     a `Parameter`) with its own passive decay toward `thetaInf` and a
//     fixed additive bump at spike time (`theta <- theta + thetaSpikeAdd`).
//     Deliberately not voltage-coupled (no `v` term in theta's own ODE) --
//     coupling theta's decay to `v` would be a more literal reproduction of
//     Allen's real GLIF4, but breaks closed-form/`expdecay` eligibility for
//     no benefit to what this ticket needs to demonstrate (a state-variable
//     threshold, integration-method selection, and spike-triggered bumps).
//   - GLIF5: GLIF3 + GLIF4 combined, unchanged otherwise.
// All five carry a refractory `Regime` pair ("integrating" initial,
// "refractory") following the IR spec §4 refractory-regime example's
// `eq`/`if`/`else` dispatch + `set_regime` pattern, with a `refractoryTimeElapsed`
// state variable ramping at a constant rate=1 (a plain forward-Euler
// `TimeDerivative`, not a special "countdown" construct) and testing
// `.geq. t_ref` to return to "integrating".

namespace {

String write_temp_file(const String &filename, const String &contents) {
    String path = (std::filesystem::temp_directory_path() / filename).string();
    std::ofstream out(path);
    out << contents;
    out.close();
    return path;
}

const TypeLibraryEntry &type_library_entry_for(const ModelSpecification &specification, const String &bound_instance_id) {
    for (const auto &entry : specification.type_library) {
        if (entry.bound_instance_id == bound_instance_id) return entry;
    }
    throw std::runtime_error("no type library entry for '" + bound_instance_id + "'");
}

// Wraps one ComponentType fixture + one bound instance into a minimal
// single-neuron network, runs it through parse -> resolve_and_lower ->
// build_model_specification, and returns the resulting cell TypeLibraryEntry.
TypeLibraryEntry build_cell_type_library_entry(const String &fixture_id, const String &component_type_xml,
                                                const String &instance_tag, const String &instance_attributes) {
    write_temp_file("spikecorec_cell_lowering_" + fixture_id + "_content.nml",
        "<neuroml xmlns=\"http://www.neuroml.org/schema/neuroml2\" id=\"CellLowering" + fixture_id + "Content\">"
        + component_type_xml +
        "  <" + instance_tag + " id=\"cellInstance\" " + instance_attributes + "/>"
        "  <network id=\"Net\">"
        "    <population id=\"Pop\" component=\"cellInstance\" size=\"1\"/>"
        "  </network>"
        "</neuroml>");

    String top_path = write_temp_file("spikecorec_cell_lowering_" + fixture_id + "_top.nml",
        "<neuroml xmlns=\"http://www.neuroml.org/schema/neuroml2\" id=\"CellLowering" + fixture_id + "Top\">"
        "  <include href=\"spikecorec_cell_lowering_" + fixture_id + "_content.nml\"/>"
        "</neuroml>");

    NML_Parser parser;
    parser.parse(top_path);
    ResolvedModel resolved = resolve_and_lower(parser);
    ModelSpecification specification = build_model_specification(resolved);
    return type_library_entry_for(specification, "cellInstance");
}

// A refractory-regime pair shared textually by every GLIF fixture below
// (only the state variable it counts down for differs, which is identical
// across all five -- `refractoryTimeElapsed`) -- kept inline per fixture
// rather than factored out, since each fixture is meant to read as one
// self-contained LEMS ComponentType, matching ticket #2/#7's own fixtures'
// style of writing the whole ComponentType out in one literal string.

const String GLIF1_COMPONENT_TYPE =
    "  <ComponentType name=\"GLIF1Cell\" extends=\"baseCell\">"
    "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
    "    <Parameter name=\"gL\" dimension=\"conductance\"/>"
    "    <Parameter name=\"EL\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vth\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vreset\" dimension=\"voltage\"/>"
    "    <Parameter name=\"t_ref\" dimension=\"time\"/>"
    "    <Attachments name=\"synapses\" type=\"basePointCurrent\"/>"
    "    <Dynamics>"
    "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
    "      <StateVariable name=\"refractoryTimeElapsed\" dimension=\"time\"/>"
    "      <DerivedVariable name=\"iSyn\" dimension=\"current\" exposure=\"iSyn\" select=\"synapses[*]/i\" reduce=\"add\"/>"
    "      <OnStart>"
    "        <StateAssignment variable=\"v\" value=\"EL\"/>"
    "        <StateAssignment variable=\"refractoryTimeElapsed\" value=\"0\"/>"
    "      </OnStart>"
    "      <Regime name=\"integrating\" initial=\"true\">"
    "        <TimeDerivative variable=\"v\" value=\"(gL * (EL - v) + iSyn) / C\"/>"
    "        <OnCondition test=\"v .gt. vth\">"
    "          <EventOut port=\"spike\"/>"
    "          <StateAssignment variable=\"v\" value=\"vreset\"/>"
    "          <Transition regime=\"refractory\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "      <Regime name=\"refractory\">"
    "        <OnEntry>"
    "          <StateAssignment variable=\"refractoryTimeElapsed\" value=\"0\"/>"
    "        </OnEntry>"
    "        <TimeDerivative variable=\"refractoryTimeElapsed\" value=\"1\"/>"
    "        <OnCondition test=\"refractoryTimeElapsed .geq. t_ref\">"
    "          <Transition regime=\"integrating\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "    </Dynamics>"
    "  </ComponentType>";

const String GLIF2_COMPONENT_TYPE =
    "  <ComponentType name=\"GLIF2Cell\" extends=\"baseCell\">"
    "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
    "    <Parameter name=\"gL\" dimension=\"conductance\"/>"
    "    <Parameter name=\"EL\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vth\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vreset\" dimension=\"voltage\"/>"
    "    <Parameter name=\"resetScale\" dimension=\"none\"/>"
    "    <Parameter name=\"t_ref\" dimension=\"time\"/>"
    "    <Attachments name=\"synapses\" type=\"basePointCurrent\"/>"
    "    <Dynamics>"
    "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
    "      <StateVariable name=\"refractoryTimeElapsed\" dimension=\"time\"/>"
    "      <DerivedVariable name=\"iSyn\" dimension=\"current\" exposure=\"iSyn\" select=\"synapses[*]/i\" reduce=\"add\"/>"
    "      <OnStart>"
    "        <StateAssignment variable=\"v\" value=\"EL\"/>"
    "      </OnStart>"
    "      <Regime name=\"integrating\" initial=\"true\">"
    "        <TimeDerivative variable=\"v\" value=\"(gL * (EL - v) + iSyn) / C\"/>"
    "        <OnCondition test=\"v .gt. vth\">"
    "          <EventOut port=\"spike\"/>"
    "          <StateAssignment variable=\"v\" value=\"vreset + resetScale * (v - vth)\"/>"
    "          <Transition regime=\"refractory\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "      <Regime name=\"refractory\">"
    "        <OnEntry>"
    "          <StateAssignment variable=\"refractoryTimeElapsed\" value=\"0\"/>"
    "        </OnEntry>"
    "        <TimeDerivative variable=\"refractoryTimeElapsed\" value=\"1\"/>"
    "        <OnCondition test=\"refractoryTimeElapsed .geq. t_ref\">"
    "          <Transition regime=\"integrating\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "    </Dynamics>"
    "  </ComponentType>";

const String GLIF3_COMPONENT_TYPE =
    "  <ComponentType name=\"GLIF3Cell\" extends=\"baseCell\">"
    "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
    "    <Parameter name=\"gL\" dimension=\"conductance\"/>"
    "    <Parameter name=\"EL\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vth\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vreset\" dimension=\"voltage\"/>"
    "    <Parameter name=\"t_ref\" dimension=\"time\"/>"
    "    <Parameter name=\"tauAsc1\" dimension=\"time\"/>"
    "    <Parameter name=\"tauAsc2\" dimension=\"time\"/>"
    "    <Parameter name=\"ascAdd1\" dimension=\"current\"/>"
    "    <Parameter name=\"ascAdd2\" dimension=\"current\"/>"
    "    <Attachments name=\"synapses\" type=\"basePointCurrent\"/>"
    "    <Dynamics>"
    "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
    "      <StateVariable name=\"asc1\" dimension=\"current\" exposure=\"asc1\"/>"
    "      <StateVariable name=\"asc2\" dimension=\"current\" exposure=\"asc2\"/>"
    "      <StateVariable name=\"refractoryTimeElapsed\" dimension=\"time\"/>"
    "      <DerivedVariable name=\"iSyn\" dimension=\"current\" exposure=\"iSyn\" select=\"synapses[*]/i\" reduce=\"add\"/>"
    "      <DerivedVariable name=\"ascSum\" dimension=\"current\" value=\"asc1 + asc2\"/>"
    "      <TimeDerivative variable=\"asc1\" value=\"-asc1 / tauAsc1\"/>"
    "      <TimeDerivative variable=\"asc2\" value=\"-asc2 / tauAsc2\"/>"
    "      <OnStart>"
    "        <StateAssignment variable=\"v\" value=\"EL\"/>"
    "        <StateAssignment variable=\"asc1\" value=\"0\"/>"
    "        <StateAssignment variable=\"asc2\" value=\"0\"/>"
    "      </OnStart>"
    "      <Regime name=\"integrating\" initial=\"true\">"
    "        <TimeDerivative variable=\"v\" value=\"(gL * (EL - v) + iSyn + ascSum) / C\"/>"
    "        <OnCondition test=\"v .gt. vth\">"
    "          <EventOut port=\"spike\"/>"
    "          <StateAssignment variable=\"v\" value=\"vreset\"/>"
    "          <StateAssignment variable=\"asc1\" value=\"asc1 + ascAdd1\"/>"
    "          <StateAssignment variable=\"asc2\" value=\"asc2 + ascAdd2\"/>"
    "          <Transition regime=\"refractory\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "      <Regime name=\"refractory\">"
    "        <OnEntry>"
    "          <StateAssignment variable=\"refractoryTimeElapsed\" value=\"0\"/>"
    "        </OnEntry>"
    "        <TimeDerivative variable=\"refractoryTimeElapsed\" value=\"1\"/>"
    "        <OnCondition test=\"refractoryTimeElapsed .geq. t_ref\">"
    "          <Transition regime=\"integrating\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "    </Dynamics>"
    "  </ComponentType>";

const String GLIF4_COMPONENT_TYPE =
    "  <ComponentType name=\"GLIF4Cell\" extends=\"baseCell\">"
    "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
    "    <Parameter name=\"gL\" dimension=\"conductance\"/>"
    "    <Parameter name=\"EL\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vreset\" dimension=\"voltage\"/>"
    "    <Parameter name=\"t_ref\" dimension=\"time\"/>"
    "    <Parameter name=\"thetaInf\" dimension=\"voltage\"/>"
    "    <Parameter name=\"tauTheta\" dimension=\"time\"/>"
    "    <Parameter name=\"thetaSpikeAdd\" dimension=\"voltage\"/>"
    "    <Attachments name=\"synapses\" type=\"basePointCurrent\"/>"
    "    <Dynamics>"
    "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
    "      <StateVariable name=\"theta\" dimension=\"voltage\" exposure=\"theta\"/>"
    "      <StateVariable name=\"refractoryTimeElapsed\" dimension=\"time\"/>"
    "      <DerivedVariable name=\"iSyn\" dimension=\"current\" exposure=\"iSyn\" select=\"synapses[*]/i\" reduce=\"add\"/>"
    "      <TimeDerivative variable=\"theta\" value=\"(thetaInf - theta) / tauTheta\"/>"
    "      <OnStart>"
    "        <StateAssignment variable=\"v\" value=\"EL\"/>"
    "        <StateAssignment variable=\"theta\" value=\"thetaInf\"/>"
    "      </OnStart>"
    "      <Regime name=\"integrating\" initial=\"true\">"
    "        <TimeDerivative variable=\"v\" value=\"(gL * (EL - v) + iSyn) / C\"/>"
    "        <OnCondition test=\"v .gt. theta\">"
    "          <EventOut port=\"spike\"/>"
    "          <StateAssignment variable=\"v\" value=\"vreset\"/>"
    "          <StateAssignment variable=\"theta\" value=\"theta + thetaSpikeAdd\"/>"
    "          <Transition regime=\"refractory\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "      <Regime name=\"refractory\">"
    "        <OnEntry>"
    "          <StateAssignment variable=\"refractoryTimeElapsed\" value=\"0\"/>"
    "        </OnEntry>"
    "        <TimeDerivative variable=\"refractoryTimeElapsed\" value=\"1\"/>"
    "        <OnCondition test=\"refractoryTimeElapsed .geq. t_ref\">"
    "          <Transition regime=\"integrating\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "    </Dynamics>"
    "  </ComponentType>";

const String GLIF5_COMPONENT_TYPE =
    "  <ComponentType name=\"GLIF5Cell\" extends=\"baseCell\">"
    "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
    "    <Parameter name=\"gL\" dimension=\"conductance\"/>"
    "    <Parameter name=\"EL\" dimension=\"voltage\"/>"
    "    <Parameter name=\"vreset\" dimension=\"voltage\"/>"
    "    <Parameter name=\"t_ref\" dimension=\"time\"/>"
    "    <Parameter name=\"thetaInf\" dimension=\"voltage\"/>"
    "    <Parameter name=\"tauTheta\" dimension=\"time\"/>"
    "    <Parameter name=\"thetaSpikeAdd\" dimension=\"voltage\"/>"
    "    <Parameter name=\"tauAsc1\" dimension=\"time\"/>"
    "    <Parameter name=\"tauAsc2\" dimension=\"time\"/>"
    "    <Parameter name=\"ascAdd1\" dimension=\"current\"/>"
    "    <Parameter name=\"ascAdd2\" dimension=\"current\"/>"
    "    <Attachments name=\"synapses\" type=\"basePointCurrent\"/>"
    "    <Dynamics>"
    "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
    "      <StateVariable name=\"theta\" dimension=\"voltage\" exposure=\"theta\"/>"
    "      <StateVariable name=\"asc1\" dimension=\"current\" exposure=\"asc1\"/>"
    "      <StateVariable name=\"asc2\" dimension=\"current\" exposure=\"asc2\"/>"
    "      <StateVariable name=\"refractoryTimeElapsed\" dimension=\"time\"/>"
    "      <DerivedVariable name=\"iSyn\" dimension=\"current\" exposure=\"iSyn\" select=\"synapses[*]/i\" reduce=\"add\"/>"
    "      <DerivedVariable name=\"ascSum\" dimension=\"current\" value=\"asc1 + asc2\"/>"
    "      <TimeDerivative variable=\"theta\" value=\"(thetaInf - theta) / tauTheta\"/>"
    "      <TimeDerivative variable=\"asc1\" value=\"-asc1 / tauAsc1\"/>"
    "      <TimeDerivative variable=\"asc2\" value=\"-asc2 / tauAsc2\"/>"
    "      <OnStart>"
    "        <StateAssignment variable=\"v\" value=\"EL\"/>"
    "        <StateAssignment variable=\"theta\" value=\"thetaInf\"/>"
    "        <StateAssignment variable=\"asc1\" value=\"0\"/>"
    "        <StateAssignment variable=\"asc2\" value=\"0\"/>"
    "      </OnStart>"
    "      <Regime name=\"integrating\" initial=\"true\">"
    "        <TimeDerivative variable=\"v\" value=\"(gL * (EL - v) + iSyn + ascSum) / C\"/>"
    "        <OnCondition test=\"v .gt. theta\">"
    "          <EventOut port=\"spike\"/>"
    "          <StateAssignment variable=\"v\" value=\"vreset\"/>"
    "          <StateAssignment variable=\"theta\" value=\"theta + thetaSpikeAdd\"/>"
    "          <StateAssignment variable=\"asc1\" value=\"asc1 + ascAdd1\"/>"
    "          <StateAssignment variable=\"asc2\" value=\"asc2 + ascAdd2\"/>"
    "          <Transition regime=\"refractory\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "      <Regime name=\"refractory\">"
    "        <OnEntry>"
    "          <StateAssignment variable=\"refractoryTimeElapsed\" value=\"0\"/>"
    "        </OnEntry>"
    "        <TimeDerivative variable=\"refractoryTimeElapsed\" value=\"1\"/>"
    "        <OnCondition test=\"refractoryTimeElapsed .geq. t_ref\">"
    "          <Transition regime=\"integrating\"/>"
    "        </OnCondition>"
    "      </Regime>"
    "    </Dynamics>"
    "  </ComponentType>";

} // namespace

// ── GLIF1: pure LIF + refractory regime ──────────────────────────────────

TEST(CellLoweringGlifFamily, lowers_glif1_leaky_integrate_and_fire_with_refractory_regime) {
    TypeLibraryEntry entry = build_cell_type_library_entry(
        "glif1", GLIF1_COMPONENT_TYPE, "GLIF1Cell",
        "C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vth=\"-50mV\" vreset=\"-70mV\" t_ref=\"5ms\"");

    IrProgram program = lower_cell_to_ir(entry);
    EXPECT_EQ(program.component_type_name, "GLIF1Cell");

    String expected =
        ".alloc\n"
        "  state v : f32 = EL\n"
        "  state refractoryTimeElapsed : f32 = 0\n"
        "  regime r\n"
        "  param C = 1e-10\n"
        "  param gL = 1e-08\n"
        "  param EL = -0.070000000000000007\n"
        "  param vth = -0.050000000000000003\n"
        "  param vreset = -0.070000000000000007\n"
        "  param t_ref = 0.0050000000000000001\n"
        "  expose v\n"
        "  expose iSyn\n"
        ".tick\n"
        "  @integrate\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      sub t0, EL, v\n"
        "      mul t0, gL, t0\n"
        "      add t0, t0, network_inputs\n"
        "      div t0, t0, C\n"
        "      mul t0, t0, dt\n"
        "      add v, v, t0\n"
        "    } else {\n"
        "      mov v, v\n"
        "    }\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      mov refractoryTimeElapsed, refractoryTimeElapsed\n"
        "    } else {\n"
        "      mov t0, 1\n"
        "      mul t0, t0, dt\n"
        "      add refractoryTimeElapsed, refractoryTimeElapsed, t0\n"
        "    }\n"
        "  @detect\n"
        "    eq is_integrating, r, 0\n"
        "    gt test_integrating, v, vth\n"
        "    and fire_integrating, is_integrating, test_integrating\n"
        "    eq is_refractory, r, 1\n"
        "    ge test_refractory, refractoryTimeElapsed, t_ref\n"
        "    and fire_refractory, is_refractory, test_refractory\n"
        "  @emit\n"
        "    if fire_integrating {\n"
        "      emit spike\n"
        "    }\n"
        "  @reset\n"
        "    if fire_integrating {\n"
        "      mov v, vreset\n"
        "      set_regime r, 1\n"
        "      mov refractoryTimeElapsed, 0\n"
        "    }\n"
        "    if fire_refractory {\n"
        "      set_regime r, 0\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);
}

// ── GLIF2: LIF + a reset rule that depends on the pre-spike voltage ──────

TEST(CellLoweringGlifFamily, lowers_glif2_voltage_dependent_reset_rule) {
    TypeLibraryEntry entry = build_cell_type_library_entry(
        "glif2", GLIF2_COMPONENT_TYPE, "GLIF2Cell",
        "C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vth=\"-50mV\" vreset=\"-70mV\" resetScale=\"0.5\" t_ref=\"5ms\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state v : f32 = EL\n"
        "  state refractoryTimeElapsed : f32\n"
        "  regime r\n"
        "  param C = 1e-10\n"
        "  param gL = 1e-08\n"
        "  param EL = -0.070000000000000007\n"
        "  param vth = -0.050000000000000003\n"
        "  param vreset = -0.070000000000000007\n"
        "  param resetScale = 0.5\n"
        "  param t_ref = 0.0050000000000000001\n"
        "  expose v\n"
        "  expose iSyn\n"
        ".tick\n"
        "  @integrate\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      sub t0, EL, v\n"
        "      mul t0, gL, t0\n"
        "      add t0, t0, network_inputs\n"
        "      div t0, t0, C\n"
        "      mul t0, t0, dt\n"
        "      add v, v, t0\n"
        "    } else {\n"
        "      mov v, v\n"
        "    }\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      mov refractoryTimeElapsed, refractoryTimeElapsed\n"
        "    } else {\n"
        "      mov t0, 1\n"
        "      mul t0, t0, dt\n"
        "      add refractoryTimeElapsed, refractoryTimeElapsed, t0\n"
        "    }\n"
        "  @detect\n"
        "    eq is_integrating, r, 0\n"
        "    gt test_integrating, v, vth\n"
        "    and fire_integrating, is_integrating, test_integrating\n"
        "    eq is_refractory, r, 1\n"
        "    ge test_refractory, refractoryTimeElapsed, t_ref\n"
        "    and fire_refractory, is_refractory, test_refractory\n"
        "  @emit\n"
        "    if fire_integrating {\n"
        "      emit spike\n"
        "    }\n"
        "  @reset\n"
        "    if fire_integrating {\n"
        "      sub t0, v, vth\n"
        "      mul t0, resetScale, t0\n"
        "      add t0, vreset, t0\n"
        "      mov v, t0\n"
        "      set_regime r, 1\n"
        "      mov refractoryTimeElapsed, 0\n"
        "    }\n"
        "    if fire_refractory {\n"
        "      set_regime r, 0\n"
        "    }\n";

    // `v = vreset + resetScale*(v - vth)` reads `v` itself inside a compound
    // sibling (`resetScale*(v-vth)`) while being assigned back into `v` --
    // exactly the self-reference shape LoweringContext::emit_expression's
    // guard exists for (see its own doc comment), so this now goes through
    // an independent `t0` and a final `mov` rather than accumulating
    // straight into `v`. Still correct either way, but this is the actual
    // path the guard takes, not just a same-answer coincidence.
    EXPECT_EQ(print_ir_program(program), expected);

    // `refractoryTimeElapsed` has no OnStart in this fixture (unlike GLIF1's)
    // -- exercises the "no initial value declared" path (nullopt, allocator
    // default) alongside GLIF1's "initial value declared" path.
    bool found_refractory_timer_without_initial_value = false;
    for (const auto &directive : program.alloc) {
        if (!std::holds_alternative<StateDirective>(directive)) continue;
        const auto &state_directive = std::get<StateDirective>(directive);
        if (state_directive.name == "refractoryTimeElapsed") {
            EXPECT_FALSE(state_directive.initial_value.has_value());
            found_refractory_timer_without_initial_value = true;
        }
    }
    EXPECT_TRUE(found_refractory_timer_without_initial_value);
}

// ── GLIF3: LIF + two after-spike currents ────────────────────────────────

TEST(CellLoweringGlifFamily, lowers_glif3_after_spike_currents) {
    TypeLibraryEntry entry = build_cell_type_library_entry(
        "glif3", GLIF3_COMPONENT_TYPE, "GLIF3Cell",
        "C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vth=\"-50mV\" vreset=\"-70mV\" t_ref=\"5ms\" "
        "tauAsc1=\"100ms\" tauAsc2=\"10ms\" ascAdd1=\"1.0e-10\" ascAdd2=\"2.0e-10\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state v : f32 = EL\n"
        "  state asc1 : f32 = 0\n"
        "  state asc2 : f32 = 0\n"
        "  state refractoryTimeElapsed : f32\n"
        "  regime r\n"
        "  param C = 1e-10\n"
        "  param gL = 1e-08\n"
        "  param EL = -0.070000000000000007\n"
        "  param vth = -0.050000000000000003\n"
        "  param vreset = -0.070000000000000007\n"
        "  param t_ref = 0.0050000000000000001\n"
        "  param tauAsc1 = 0.10000000000000001\n"
        "  param tauAsc2 = 0.01\n"
        "  param ascAdd1 = 1e-10\n"
        "  param ascAdd2 = 2.0000000000000001e-10\n"
        "  expose v\n"
        "  expose asc1\n"
        "  expose asc2\n"
        "  expose iSyn\n"
        ".tick\n"
        "  @integrate\n"
        "    add ascSum, asc1, asc2\n"
        "    expdecay asc1, asc1, tauAsc1\n"
        "    expdecay asc2, asc2, tauAsc2\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      sub t0, EL, v\n"
        "      mul t0, gL, t0\n"
        "      add t0, t0, network_inputs\n"
        "      add t0, t0, ascSum\n"
        "      div t0, t0, C\n"
        "      mul t0, t0, dt\n"
        "      add v, v, t0\n"
        "    } else {\n"
        "      mov v, v\n"
        "    }\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      mov refractoryTimeElapsed, refractoryTimeElapsed\n"
        "    } else {\n"
        "      mov t0, 1\n"
        "      mul t0, t0, dt\n"
        "      add refractoryTimeElapsed, refractoryTimeElapsed, t0\n"
        "    }\n"
        "  @detect\n"
        "    eq is_integrating, r, 0\n"
        "    gt test_integrating, v, vth\n"
        "    and fire_integrating, is_integrating, test_integrating\n"
        "    eq is_refractory, r, 1\n"
        "    ge test_refractory, refractoryTimeElapsed, t_ref\n"
        "    and fire_refractory, is_refractory, test_refractory\n"
        "  @emit\n"
        "    if fire_integrating {\n"
        "      emit spike\n"
        "    }\n"
        "  @reset\n"
        "    if fire_integrating {\n"
        "      mov v, vreset\n"
        "      add asc1, asc1, ascAdd1\n"
        "      add asc2, asc2, ascAdd2\n"
        "      set_regime r, 1\n"
        "      mov refractoryTimeElapsed, 0\n"
        "    }\n"
        "    if fire_refractory {\n"
        "      set_regime r, 0\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);
}

// ── GLIF4: LIF + an adaptive (state-variable) threshold ──────────────────

TEST(CellLoweringGlifFamily, lowers_glif4_adaptive_threshold) {
    TypeLibraryEntry entry = build_cell_type_library_entry(
        "glif4", GLIF4_COMPONENT_TYPE, "GLIF4Cell",
        "C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vreset=\"-70mV\" t_ref=\"5ms\" "
        "thetaInf=\"-50mV\" tauTheta=\"50ms\" thetaSpikeAdd=\"5mV\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state v : f32 = EL\n"
        "  state theta : f32 = thetaInf\n"
        "  state refractoryTimeElapsed : f32\n"
        "  regime r\n"
        "  param C = 1e-10\n"
        "  param gL = 1e-08\n"
        "  param EL = -0.070000000000000007\n"
        "  param vreset = -0.070000000000000007\n"
        "  param t_ref = 0.0050000000000000001\n"
        "  param thetaInf = -0.050000000000000003\n"
        "  param tauTheta = 0.050000000000000003\n"
        "  param thetaSpikeAdd = 0.0050000000000000001\n"
        "  expose v\n"
        "  expose theta\n"
        "  expose iSyn\n"
        ".tick\n"
        "  @integrate\n"
        "    sub theta, theta, thetaInf\n"
        "    expdecay theta, theta, tauTheta\n"
        "    add theta, theta, thetaInf\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      sub t0, EL, v\n"
        "      mul t0, gL, t0\n"
        "      add t0, t0, network_inputs\n"
        "      div t0, t0, C\n"
        "      mul t0, t0, dt\n"
        "      add v, v, t0\n"
        "    } else {\n"
        "      mov v, v\n"
        "    }\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      mov refractoryTimeElapsed, refractoryTimeElapsed\n"
        "    } else {\n"
        "      mov t0, 1\n"
        "      mul t0, t0, dt\n"
        "      add refractoryTimeElapsed, refractoryTimeElapsed, t0\n"
        "    }\n"
        "  @detect\n"
        "    eq is_integrating, r, 0\n"
        "    gt test_integrating, v, theta\n"
        "    and fire_integrating, is_integrating, test_integrating\n"
        "    eq is_refractory, r, 1\n"
        "    ge test_refractory, refractoryTimeElapsed, t_ref\n"
        "    and fire_refractory, is_refractory, test_refractory\n"
        "  @emit\n"
        "    if fire_integrating {\n"
        "      emit spike\n"
        "    }\n"
        "  @reset\n"
        "    if fire_integrating {\n"
        "      mov v, vreset\n"
        "      add theta, theta, thetaSpikeAdd\n"
        "      set_regime r, 1\n"
        "      mov refractoryTimeElapsed, 0\n"
        "    }\n"
        "    if fire_refractory {\n"
        "      set_regime r, 0\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);

    // Threshold-vs-state-variable acceptance criterion: the detect stage
    // compares `v` against `theta` (a StateVariable), not a Parameter.
    EXPECT_NE(print_ir_program(program).find("gt test_integrating, v, theta"), String::npos);
}

// ── GLIF5: GLIF3 + GLIF4 combined ────────────────────────────────────────

TEST(CellLoweringGlifFamily, lowers_glif5_after_spike_currents_and_adaptive_threshold) {
    TypeLibraryEntry entry = build_cell_type_library_entry(
        "glif5", GLIF5_COMPONENT_TYPE, "GLIF5Cell",
        "C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vreset=\"-70mV\" t_ref=\"5ms\" "
        "thetaInf=\"-50mV\" tauTheta=\"50ms\" thetaSpikeAdd=\"5mV\" "
        "tauAsc1=\"100ms\" tauAsc2=\"10ms\" ascAdd1=\"1.0e-10\" ascAdd2=\"2.0e-10\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state v : f32 = EL\n"
        "  state theta : f32 = thetaInf\n"
        "  state asc1 : f32 = 0\n"
        "  state asc2 : f32 = 0\n"
        "  state refractoryTimeElapsed : f32\n"
        "  regime r\n"
        "  param C = 1e-10\n"
        "  param gL = 1e-08\n"
        "  param EL = -0.070000000000000007\n"
        "  param vreset = -0.070000000000000007\n"
        "  param t_ref = 0.0050000000000000001\n"
        "  param thetaInf = -0.050000000000000003\n"
        "  param tauTheta = 0.050000000000000003\n"
        "  param thetaSpikeAdd = 0.0050000000000000001\n"
        "  param tauAsc1 = 0.10000000000000001\n"
        "  param tauAsc2 = 0.01\n"
        "  param ascAdd1 = 1e-10\n"
        "  param ascAdd2 = 2.0000000000000001e-10\n"
        "  expose v\n"
        "  expose theta\n"
        "  expose asc1\n"
        "  expose asc2\n"
        "  expose iSyn\n"
        ".tick\n"
        "  @integrate\n"
        "    add ascSum, asc1, asc2\n"
        "    sub theta, theta, thetaInf\n"
        "    expdecay theta, theta, tauTheta\n"
        "    add theta, theta, thetaInf\n"
        "    expdecay asc1, asc1, tauAsc1\n"
        "    expdecay asc2, asc2, tauAsc2\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      sub t0, EL, v\n"
        "      mul t0, gL, t0\n"
        "      add t0, t0, network_inputs\n"
        "      add t0, t0, ascSum\n"
        "      div t0, t0, C\n"
        "      mul t0, t0, dt\n"
        "      add v, v, t0\n"
        "    } else {\n"
        "      mov v, v\n"
        "    }\n"
        "    eq is_integrating, r, 0\n"
        "    if is_integrating {\n"
        "      mov refractoryTimeElapsed, refractoryTimeElapsed\n"
        "    } else {\n"
        "      mov t0, 1\n"
        "      mul t0, t0, dt\n"
        "      add refractoryTimeElapsed, refractoryTimeElapsed, t0\n"
        "    }\n"
        "  @detect\n"
        "    eq is_integrating, r, 0\n"
        "    gt test_integrating, v, theta\n"
        "    and fire_integrating, is_integrating, test_integrating\n"
        "    eq is_refractory, r, 1\n"
        "    ge test_refractory, refractoryTimeElapsed, t_ref\n"
        "    and fire_refractory, is_refractory, test_refractory\n"
        "  @emit\n"
        "    if fire_integrating {\n"
        "      emit spike\n"
        "    }\n"
        "  @reset\n"
        "    if fire_integrating {\n"
        "      mov v, vreset\n"
        "      add theta, theta, thetaSpikeAdd\n"
        "      add asc1, asc1, ascAdd1\n"
        "      add asc2, asc2, ascAdd2\n"
        "      set_regime r, 1\n"
        "      mov refractoryTimeElapsed, 0\n"
        "    }\n"
        "    if fire_refractory {\n"
        "      set_regime r, 0\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);
}

// ── Fidelity check: a Regime-less LIF cell reproduces the locked IR spec's
// own GLIF1 example (docs/nml_ir_spec.md §4) almost exactly -- the ticket's
// "should already lower cleanly" instruction for the base case, kept
// separate from the five (regime-carrying) GLIF fixtures above per this
// ticket's own documented resolution of that tension (see this file's
// header comment). Written with `network_inputs` referenced directly
// (bypassing the DerivedVariable/select/reduce alias) and with it as the
// FIRST addend, purely so the produced instructions match the spec's
// exact operand order -- everywhere else in this file the more realistic
// `iSyn`-DerivedVariable-alias form is used instead, and its commutative
// (but equivalent) reordering of that one `add` is expected, not a bug --
// see LoweringContext::emit_expression's own doc comment. ─────────────────

TEST(CellLoweringGlifFamily, lowers_regime_less_lif_cell_matching_locked_ir_spec_glif1_example) {
    const String component_type =
        "  <ComponentType name=\"PlainLifCell\" extends=\"baseCell\">"
        "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
        "    <Parameter name=\"gL\" dimension=\"conductance\"/>"
        "    <Parameter name=\"EL\" dimension=\"voltage\"/>"
        "    <Parameter name=\"vth\" dimension=\"voltage\"/>"
        "    <Parameter name=\"vreset\" dimension=\"voltage\"/>"
        "    <Dynamics>"
        "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
        "      <TimeDerivative variable=\"v\" value=\"(network_inputs + gL * (EL - v)) / C\"/>"
        "      <OnCondition test=\"v .gt. vth\">"
        "        <EventOut port=\"spike\"/>"
        "        <StateAssignment variable=\"v\" value=\"vreset\"/>"
        "      </OnCondition>"
        "    </Dynamics>"
        "  </ComponentType>";

    TypeLibraryEntry entry = build_cell_type_library_entry(
        "plainlif", component_type, "PlainLifCell",
        "C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vth=\"-50mV\" vreset=\"-70mV\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state v : f32\n"
        "  param C = 1e-10\n"
        "  param gL = 1e-08\n"
        "  param EL = -0.070000000000000007\n"
        "  param vth = -0.050000000000000003\n"
        "  param vreset = -0.070000000000000007\n"
        "  expose v\n"
        ".tick\n"
        "  @integrate\n"
        "    sub t0, EL, v\n"
        "    mul t0, gL, t0\n"
        "    add t0, network_inputs, t0\n"
        "    div t0, t0, C\n"
        "    mul t0, t0, dt\n"
        "    add v, v, t0\n"
        "  @detect\n"
        "    gt spiked, v, vth\n"
        "  @emit\n"
        "    if spiked {\n"
        "      emit spike\n"
        "    }\n"
        "  @reset\n"
        "    if spiked {\n"
        "      mov v, vreset\n"
        "    }\n";

    // This is exactly docs/nml_ir_spec.md §4's GLIF1 example's `.tick`
    // section (its `.alloc` elides literal values as bare `param` names;
    // here they're baked, per ticket #7's Phase-1 rule).
    EXPECT_EQ(print_ir_program(program), expected);
}

// ── Error handling ────────────────────────────────────────────────────────

TEST(CellLoweringErrors, throws_on_undeclared_identifier_in_time_derivative) {
    const String component_type =
        "  <ComponentType name=\"BrokenCell\" extends=\"baseCell\">"
        "    <Parameter name=\"C\" dimension=\"capacitance\"/>"
        "    <Dynamics>"
        "      <StateVariable name=\"v\" dimension=\"voltage\" exposure=\"v\"/>"
        "      <TimeDerivative variable=\"v\" value=\"undeclaredQuantity / C\"/>"
        "    </Dynamics>"
        "  </ComponentType>";

    TypeLibraryEntry entry = build_cell_type_library_entry("broken", component_type, "BrokenCell", "C=\"1.0e-10\"");

    EXPECT_THROW(lower_cell_to_ir(entry), std::runtime_error);
}

TEST(CellLoweringErrors, throws_when_lowering_a_non_cell_type_library_entry) {
    const String component_type =
        "  <ComponentType name=\"BareSynapse\" extends=\"baseSynapse\">"
        "    <Parameter name=\"tau\" dimension=\"time\"/>"
        "    <Dynamics>"
        "      <StateVariable name=\"g\" dimension=\"conductance\" exposure=\"g\"/>"
        "      <TimeDerivative variable=\"g\" value=\"-g / tau\"/>"
        "    </Dynamics>"
        "  </ComponentType>";

    TypeLibraryEntry entry = build_cell_type_library_entry("synapse", component_type, "BareSynapse", "tau=\"2ms\"");
    ASSERT_EQ(entry.category, TypeLibraryCategory::Synapse);

    EXPECT_THROW(lower_cell_to_ir(entry), std::runtime_error);
}

// ── lower_all_cell_types_to_ir: only Cell-category entries get lowered ───

TEST(CellLoweringGlifFamily, lower_all_cell_types_skips_non_cell_type_library_entries) {
    write_temp_file("spikecorec_cell_lowering_mixed_content.nml",
        "<neuroml xmlns=\"http://www.neuroml.org/schema/neuroml2\" id=\"CellLoweringMixedContent\">"
        + GLIF1_COMPONENT_TYPE +
        "  <GLIF1Cell id=\"glif1Instance\" C=\"1.0e-10\" gL=\"1.0e-8\" EL=\"-70mV\" vth=\"-50mV\" vreset=\"-70mV\" t_ref=\"5ms\"/>"
        "  <expOneSynapse id=\"excSynapse\" gbase=\"1nS\" erev=\"0mV\" tauDecay=\"3ms\"/>"
        "  <network id=\"Net\">"
        "    <population id=\"Pop\" component=\"glif1Instance\" size=\"1\"/>"
        "    <projection id=\"SelfLoop\" presynapticPopulation=\"Pop\" postsynapticPopulation=\"Pop\" synapse=\"excSynapse\">"
        "      <connection id=\"0\" preCellId=\"Pop/0/glif1Instance\" postCellId=\"Pop/0/glif1Instance\"/>"
        "    </projection>"
        "  </network>"
        "</neuroml>");
    String top_path = write_temp_file("spikecorec_cell_lowering_mixed_top.nml",
        "<neuroml xmlns=\"http://www.neuroml.org/schema/neuroml2\" id=\"CellLoweringMixedTop\">"
        "  <include href=\"spikecorec_cell_lowering_mixed_content.nml\"/>"
        "</neuroml>");

    NML_Parser parser;
    parser.parse(top_path);
    ResolvedModel resolved = resolve_and_lower(parser);
    ModelSpecification specification = build_model_specification(resolved);
    ASSERT_EQ(specification.type_library.size(), 2u); // one cell, one synapse

    Vector<IrProgram> programs = lower_all_cell_types_to_ir(specification);
    ASSERT_EQ(programs.size(), 1u);
    EXPECT_EQ(programs[0].component_type_name, "GLIF1Cell");
}

// ── Register-aliasing guard (review follow-up on ticket #50) ─────────────
//
// `LoweringContext::emit_expression` accumulates a compound operand directly
// into the destination register requested by its caller (see its own doc
// comment) -- if that destination aliases an identifier ALSO read elsewhere
// in the same expression (a self-referential update, e.g. a saturating
// synapse's `g <- g + gbase*(1-g)`), accumulating the compound sibling
// straight into that shared register would clobber the identifier's value
// before the rest of the expression reads it. This is exactly the shape
// ticket #51's synapse lowering will need (a bounded conductance update),
// not just a contrived cell fixture -- reproduced here as a minimal
// standalone CellType instead of a full GLIF variant, since the hazard is a
// property of `emit_expression` itself, independent of GLIF.

TEST(CellLoweringRegisterAliasingGuard, self_referential_saturating_update_lowers_correctly) {
    const String component_type =
        "  <ComponentType name=\"SaturatingResetCell\" extends=\"baseCell\">"
        "    <Parameter name=\"gbase\" dimension=\"none\"/>"
        "    <Parameter name=\"threshold\" dimension=\"none\"/>"
        "    <Dynamics>"
        "      <StateVariable name=\"g\" dimension=\"none\" exposure=\"g\"/>"
        "      <OnCondition test=\"g .gt. threshold\">"
        "        <StateAssignment variable=\"g\" value=\"g + gbase * (1 - g)\"/>"
        "      </OnCondition>"
        "    </Dynamics>"
        "  </ComponentType>";

    TypeLibraryEntry entry = build_cell_type_library_entry(
        "saturating", component_type, "SaturatingResetCell", "gbase=\"0.1\" threshold=\"0.5\"");

    IrProgram program = lower_cell_to_ir(entry);

    // Correct lowering evaluates the whole right-hand side into an
    // independent temporary FIRST (so the read of `g` inside `1 - g` still
    // observes the pre-update value), then copies the result into `g` --
    // never accumulating directly into `g` mid-computation. The buggy
    // (pre-fix) behavior would instead emit `sub g,1,g / mul g,gbase,g /
    // add g,g,g`, silently computing `2*gbase*(1-g)` instead of
    // `g + gbase*(1-g)`.
    String expected =
        ".alloc\n"
        "  state g : f32\n"
        "  param gbase = 0.10000000000000001\n"
        "  param threshold = 0.5\n"
        "  expose g\n"
        ".tick\n"
        "  @detect\n"
        "    gt spiked, g, threshold\n"
        "  @reset\n"
        "    if spiked {\n"
        "      sub t0, 1, g\n"
        "      mul t0, gbase, t0\n"
        "      add t0, g, t0\n"
        "      mov g, t0\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);
}

// Same hazard, arithmetic-only shape (the reviewer's own minimal example):
// `v <- v + v*k` written back into `v` -- `v` appears both as a plain leaf
// operand and, separately, inside the compound sibling.
TEST(CellLoweringRegisterAliasingGuard, self_multiplying_reset_lowers_correctly) {
    const String component_type =
        "  <ComponentType name=\"SelfMultiplyResetCell\" extends=\"baseCell\">"
        "    <Parameter name=\"k\" dimension=\"none\"/>"
        "    <Parameter name=\"threshold\" dimension=\"none\"/>"
        "    <Dynamics>"
        "      <StateVariable name=\"v\" dimension=\"none\" exposure=\"v\"/>"
        "      <OnCondition test=\"v .gt. threshold\">"
        "        <StateAssignment variable=\"v\" value=\"v + v * k\"/>"
        "      </OnCondition>"
        "    </Dynamics>"
        "  </ComponentType>";

    TypeLibraryEntry entry = build_cell_type_library_entry(
        "selfmultiply", component_type, "SelfMultiplyResetCell", "k=\"0.2\" threshold=\"0.5\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state v : f32\n"
        "  param k = 0.20000000000000001\n"
        "  param threshold = 0.5\n"
        "  expose v\n"
        ".tick\n"
        "  @detect\n"
        "    gt spiked, v, threshold\n"
        "  @reset\n"
        "    if spiked {\n"
        "      mul t0, v, k\n"
        "      add t0, v, t0\n"
        "      mov v, t0\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);
}

// A same-identifier, both-leaf self-reference (`asc1 <- asc1 + ascAdd1`,
// already exercised inline within the GLIF3/5 fixtures above) must NOT be
// pessimized by the guard -- a single leaf-leaf combine is atomic and safe
// regardless of aliasing, so it should stay a one-instruction `add`.
TEST(CellLoweringRegisterAliasingGuard, leaf_only_self_reference_stays_a_single_instruction) {
    const String component_type =
        "  <ComponentType name=\"LeafBumpResetCell\" extends=\"baseCell\">"
        "    <Parameter name=\"bumpAmount\" dimension=\"none\"/>"
        "    <Parameter name=\"threshold\" dimension=\"none\"/>"
        "    <Dynamics>"
        "      <StateVariable name=\"g\" dimension=\"none\" exposure=\"g\"/>"
        "      <OnCondition test=\"g .gt. threshold\">"
        "        <StateAssignment variable=\"g\" value=\"g + bumpAmount\"/>"
        "      </OnCondition>"
        "    </Dynamics>"
        "  </ComponentType>";

    TypeLibraryEntry entry = build_cell_type_library_entry(
        "leafbump", component_type, "LeafBumpResetCell", "bumpAmount=\"0.1\" threshold=\"0.5\"");

    IrProgram program = lower_cell_to_ir(entry);

    String expected =
        ".alloc\n"
        "  state g : f32\n"
        "  param bumpAmount = 0.10000000000000001\n"
        "  param threshold = 0.5\n"
        "  expose g\n"
        ".tick\n"
        "  @detect\n"
        "    gt spiked, g, threshold\n"
        "  @reset\n"
        "    if spiked {\n"
        "      add g, g, bumpAmount\n"
        "    }\n";

    EXPECT_EQ(print_ir_program(program), expected);
}
